name: Validate

on: [push]
jobs:
  validate-linux:
    strategy:
      matrix:
        runner: [ubuntu-22.04]
        package: [example-nih-plug, example-clack]
        include:
          - package: example-nih-plug
            library_name: libexample_nih_plug.so
            plugin_name: Gain GUI (VIZIA)
          - package: example-clack
            library_name: libexample_clack.so
            plugin_name: Clack PolySynth Example

    name: Validate "${{ matrix.package }}" (${{ matrix.runner }})
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
            submodules: recursive

      - name: Install dependencies
        shell: bash
        run: |
            # needed for baseview and other example-nih-plug deps
            sudo apt-get install -y libgl-dev libx11-xcb-dev libxcb1-dev libxcb-dri2-0-dev libxcb-icccm4-dev libxcursor-dev libxkbcommon-dev libxcb-shape0-dev libxcb-xfixes0-dev

      - name: Package `clap-wrapper`
        shell: bash
        run: |
            # we test the packaged version to make sure everything needed is included
            cargo package -p clap-wrapper

      - name: Build `${{ matrix.package }}`
        shell: bash
        run: |
            cargo build -p ${{ matrix.package }}
            cargo bundle target/debug/${{ matrix.library_name }}

      - name: Upload VST3
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.package }}-${{ matrix.runner }}-vst3
          path: ./target/debug/${{ matrix.plugin_name }}.vst3
          retention-days: 30

      - name: Build `vst3-validator`
        shell: bash
        run: |
            git clone --depth=1 https://github.com/steinbergmedia/vst3sdk
            cd vst3sdk
            git submodule update --init base
            git submodule update --init cmake
            git submodule update --init public.sdk
            git submodule update --init pluginterfaces
            cmake -DSMTG_ENABLE_VSTGUI_SUPPORT=OFF -DSMTG_ENABLE_VST3_PLUGIN_EXAMPLES=OFF -DSMTG_ENABLE_VST3_HOSTING_EXAMPLES=OFF -B cmake-build 
            cmake --build cmake-build --target validator
            cd ..

      - name: Run `vst3-validator`
        shell: bash
        run: |
            "./vst3sdk/cmake-build/bin/validator" -e "./target/debug/${{ matrix.plugin_name }}.vst3" 

  validate-windows:
    strategy:
      matrix:
        runner: [windows-2022]
        package: [example-nih-plug, example-clack]
        include:
          - package: example-nih-plug
            library_name: example_nih_plug.dll
            plugin_name: Gain GUI (VIZIA)
          - package: example-clack
            library_name: example_clack.dll
            plugin_name: Clack PolySynth Example

    name: Validate "${{ matrix.package }}" (${{ matrix.runner }})
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
            submodules: recursive

      - name: Package `clap-wrapper`
        shell: bash
        run: |
            # we test the packaged version to make sure everything needed is included
            cargo package -p clap-wrapper

      - name: Build `${{ matrix.package }}`
        shell: bash
        run: |
            cargo build -p ${{ matrix.package }}
            cargo bundle target/debug/${{ matrix.library_name }}

      - name: Upload VST3
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.package }}-${{ matrix.runner }}-vst3
          path: ./target/debug/${{ matrix.plugin_name }}.vst3
          retention-days: 30

      - name: Build `vst3-validator`
        shell: bash
        run: |
            git clone --depth=1 https://github.com/steinbergmedia/vst3sdk
            cd vst3sdk
            git submodule update --init base
            git submodule update --init cmake
            git submodule update --init public.sdk
            git submodule update --init pluginterfaces
            cmake -DSMTG_ENABLE_VSTGUI_SUPPORT=OFF -DSMTG_ENABLE_VST3_PLUGIN_EXAMPLES=OFF -DSMTG_ENABLE_VST3_HOSTING_EXAMPLES=OFF -B cmake-build 
            cmake --build cmake-build --target validator
            cd ..

      - name: Run `vst3-validator`
        shell: bash
        run: |
            "./vst3sdk/cmake-build/bin/Debug/validator" -e "./target/debug/${{ matrix.plugin_name }}.vst3" 
      
  validate-macos:
    strategy:
      matrix:
        runner: [macos-15]
        package: [example-nih-plug, example-clack]
        include:
          - package: example-nih-plug
            library_name: libexample_nih_plug.dylib
            plugin_name: Gain GUI (VIZIA)
            auv2_type: aufx
            auv2_subtype: gain
            auv2_manufacturer: Mois
          - package: example-clack
            library_name: libexample_clack.dylib
            plugin_name: Clack PolySynth Example
            auv2_type: aumu
            auv2_subtype: psyn
            auv2_manufacturer: Clck

    name: Validate "${{ matrix.package }}" (${{ matrix.runner }})
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
            submodules: recursive

      - name: Package `clap-wrapper`
        shell: bash
        run: |
            # we test the packaged version to make sure everything needed is included
            cargo package -p clap-wrapper

      - name: Build `${{ matrix.package }}`
        shell: bash
        run: |
            cargo build -p ${{ matrix.package }}
            cargo bundle -i --auv2-id ${{ matrix.auv2_type }}:${{ matrix.auv2_subtype }}:${{ matrix.auv2_manufacturer }} target/debug/${{ matrix.library_name }}

      - name: Upload AUv2
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.package }}-${{ matrix.runner }}-auv2
          path: ./target/debug/${{ matrix.plugin_name }}.component
          retention-days: 30

      - name: Upload VST3
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.package }}-${{ matrix.runner }}-vst3
          path: ./target/debug/${{ matrix.plugin_name }}.vst3
          retention-days: 30

      - name: Build `vst3-validator`
        shell: bash
        run: |
            git clone --depth=1 https://github.com/steinbergmedia/vst3sdk
            cd vst3sdk
            git submodule update --init base
            git submodule update --init cmake
            git submodule update --init public.sdk
            git submodule update --init pluginterfaces
            cmake -DSMTG_ENABLE_VSTGUI_SUPPORT=OFF -DSMTG_ENABLE_VST3_PLUGIN_EXAMPLES=OFF -DSMTG_ENABLE_VST3_HOSTING_EXAMPLES=OFF -B cmake-build 
            cmake --build cmake-build --target validator
            cd ..

      - name: Run `vst3-validator`
        shell: bash
        run: |
            "./vst3sdk/cmake-build/bin/validator" -e "./target/debug/${{ matrix.plugin_name }}.vst3" 

      - name: Run `auval`
        shell: bash
        run: |
            auval -a
            auval -strict -v ${{ matrix.auv2_type }} ${{ matrix.auv2_subtype }} ${{ matrix.auv2_manufacturer }}